---
#CampaignManager DB backup
- name: List databases
  shell: "mysql -uroot -p{{ vault_root_passwd }} -e 'show databases'"
  register: databases

- name: Dump  databases
  mysql_db:
   state: dump
   login_user: root
   login_password: "{{ vault_root_passwd }}"
   config_file: /etc/my.cnf
   name: replica_cm_6_0_4_0
   target: /tmp/{{ item }}.sql
  with_items:
    - "{{ databases.stdout_lines|difference(exclude_db) }}"

- name: Fetch data from Remote Server
  fetch:
   src: "/tmp/{{ item }}.sql"
   dest: /var/tmp/
   flat: yes
  with_items:
    - "{{ databases.stdout_lines|difference(exclude_db) }}"
